---
- name: Install common packages
  apt:
    name: "Softwares"
    state: present
  loop:
    - vim
    - curl
    - telnet
    - unzip
    - wget
    - net-tools
    - htop
    - nmap

- name: Update package list
  apt_update:
    update_cache: yes

- name: Set machine name
  hostname:
    name: sueleido

- name: Create user sueleido
  user:
    name: sueleido
    state: present

- name: Create SSH key for user sueleido
  user:
    name: sueleido
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
